variables:
  CI_REGISTRY: "registry.gitlab.com"
  PROJECT_REGISTRY: "$CI_REGISTRY/hmajid2301/gitlab-auto-mr"

stages:
  - publish


publish-package:production:
  image: python:3.6
  stage: publish
  only:
    - /^release/.*$/
  variables:
    TWINE_USERNAME: $PYPI_PRODUCTION_USERNAME
    TWINE_PASSWORD: $PYPI_PRODUCTION_PASSWORD
  before_script:
    - pip install twine
    - python setup.py sdist
  script:
    - twine check dist/*
    - twine upload dist/*


publish-docker:
  stage: publish
  image: docker
  before_script:
    - apk add python3-dev
    - python setup.py sdist
  script:
    - docker login ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_BUILD_TOKEN}
    - docker build -t ${PROJECT_REGISTRY}:latest  .
    - docker push ${PROJECT_REGISTRY}:latest


