variables:
  CI_REGISTRY: "registry.gitlab.com"
  PROJECT_REGISTRY: "$CI_REGISTRY/hmajid2301/gitlab-auto-mr"
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - publish


test:linter:
  stage: test
  image: alpine/flake8
  script:
    - flake8 src/


test:code-formatter:
  stage: test
  image: milansuk/python-black:latest
  script:
    - black --check src/


publish-package:production:
  stage: publish
  image: python:3.6
  only:
    - /^release/.*$/
  variables:
    TWINE_USERNAME: $PYPI_PRODUCTION_USERNAME
    TWINE_PASSWORD: $PYPI_PRODUCTION_PASSWORD
  before_script:
    - pip install twine
    - python setup.py sdist
  script:
    - twine check dist/*
    - twine upload dist/*


publish-docker:
  stage: publish
  image: docker
  before_script:
    - apk add python3-dev
    - python3 setup.py sdist
  script:
    - docker login ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_BUILD_TOKEN}
    - docker build -t ${PROJECT_REGISTRY}:latest  .
    - docker push ${PROJECT_REGISTRY}:latest